### ISSUE TITLE
SFSafariViewController has issues with landscape view

### ISSUE THREAD

**Issue by tomkidd** [latestchatty/latest-chatty-2#136]
If I launch a web link with SFSafariViewController in portrait and go back to the main app all is well. 

If I launch it in landscape mode, when I go back to the main app, the main app is in portrait mode (even though it was in landscape mode when I launched the link) and I have to turn the phone to portrait, wait a second, then turn it back to landscape to get the app back in landscape mode.

**Comment by patch-e** [comment]
This should all go away with the pending update I am working on. There won't be any iPhone landscape support anymore EXCEPT for when in SFSafariViewControllers. This way videos and images can be rotated / full screen'd.

**Comment by patch-e** [comment]
This was indirectly resolved back with [commit](url
https://github.com/latestchatty/latest-chatty-2/commit/e42a3c01e62f7c57fdf68315283bd45395a8b985) and released in version 4.8.0.

Landscape for iPhone was removed completely but the "Safari View" browser preference setting (which uses SFSafariViewController) supports portrait and landscape.
